pipeline {
    agent any

    environment {
        IMAGE_NAME = "docker_jenkins_app"
        TAG = "latest"
    }

    stages {
        stage('Restore') {
            steps {
                sh 'dotnet restore Docker_Jenkins.sln'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build --configuration Release Docker_Jenkins.sln'
            }
        }

        stage('Publish') {
            steps {
                sh 'dotnet publish -c Release -o out Docker_Jenkins/Docker_Jenkins.csproj'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG Docker_Jenkins'
            }
        }
    }
}
