pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Exemple si tu as un repo Git, sinon supprime cette étape
                // git 'https://github.com/ton-compte/ton-projet.git'
                echo 'Pas de checkout, on fait juste un test.'
            }
        }
        stage('Build .NET') {
            steps {
                echo 'Compilation .NET'
                sh 'dotnet --version'  // juste pour vérifier que .NET est là
                // ici tu peux ajouter : sh 'dotnet build ton-projet.sln'
            }
        }
        stage('Docker version') {
            steps {
                sh 'docker --version' // vérifier que Docker CLI est dispo
            }
        }
    }
}
